### ISSUE TITLE
reservation 함수가 어디에 정의되어 있나요?

### ISSUE THREAD

**Issue by akaxan** [potados99/melon-ticket-helper#3]
안녕하세요.
js 공부하다 찾아오게 되었습니다.
제공해주신 코드 실행하면
"schedules.js:74 Uncaught (in promise) ReferenceError: reservation is not defined
    at doScheduleMagic (schedules.js:74:3)
    at schedules.js:85:33
    at common.js:28:9"
위와 같은 에러가 나와서, 소스를 살펴봐도 reservation 함수를 못찾았습니다.
어딘가에 정의 되어 있어야 할 것 같은데
제가 잘못 이해한 것 일까요?
시간이 좀 지났습니다만, 답변해주시면 정말 감사하겠습니다.

**Comment by rladpwns12** [comment]
저도 분석해보고 있는데 제 추측으로는 아마 멜론에서 만들어둔 함수명이 본래 reservation 이였는데, potados99님께서1년전에 만들었다보니 멜론에서 함수명과 파라메터 수정으로 찾지 못하는것 같습니다. 비슷한 함수인 _IReservation() 함수를 찾아볼 수 있는데 참고해보세요.

**Comment by rladpwns12** [comment]
그리고 함수가 수정 되더라도 파라메터가 작년 아이유 콘서트로 하드코딩 되어있어서 실질적 사용은 안되실겁니다. 상황에 맞게 변경 하시거나 prodId 값 정도는 동적으로 불러와 저장하고 선예매용, 일반예매용 나눠서 짜셔야 할것같습니다.

**Comment by potados99** [comment]
@akaxan 안녕하세요! 답이 늦어 죄송합니다. 당시 멜론티켓 API와 클라이언트쪽 스크립트에 맞춰 코드를 작성하였는데, 아무래도 마지막으로 작동을 확인한 이후로 1년이 넘게 흐르다 보니 사이트에 변화가 생겨 더이상 작동하지 않는 상황인 것 같습니다. 개인적으로 이 프로젝트의 유지보수는 후순위로 밀려 있어 아마 당분간은 업데이트를 하지 못할 것 같습니다😢

**Comment by potados99** [comment]
@rladpwns12 답변 달아주셔서 감사합니다🥹 최근에 멜론티켓 API를 들여다본 적이 없어 변화가 생긴 줄도 모르고 있었습니다. 자세하게 알려주셔서 감사합니다!

**Comment by yebeing** [comment]
안녕하세요 혹시 최근 멜론 티켓 콘서트에 적용가능하게 업데이트 하실 예정은 없으실까요 🥺 내용이 많아 어려우시다면 직링 만드는 방법이라도 알고 싶어요 어떻게 만드시는 건지 궁금합니당 ...
